all: zad1 zad2

zad1:
	ifort -std08 zad1.F90 -o zad1 -L/home/michalek/Documents/Fortran/zadanie2/src/fftw-3.3.8/.libs -lfftw3

zad2:
	ifort -std08 zad2.F90 -o zad2 -L/home/michalek/Documents/Fortran/zadanie2/src/fftw-3.3.8/.libs -lfftw3
